### ISSUE TITLE
Charge中deleteChargeById接口出现问题

### ISSUE THREAD

**Issue by iafchu** [phsz-dev/phsz-backend#16]
接口在执行删除操作前未提供确认步骤，任何具有删除权限的用户均可直接删除，数据可能因误操作或恶意行为而被删除，造成不可逆的损失。

**Comment by JustinMoFeng** [comment]
接口本身不应存在确认步骤，只是需要鉴别是否有删除权限，对于误操作的问题，可以使用redis进行删除保存，在前端可以让用户进行操作回复。
